spring:
  kafka:
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  application:
    name: hw2
  datasource:
#    url: ${DATABASE_URL}
    url: jdbc:postgresql://localhost:5432/postgres
#    username: ${DATABASE_USERNAME}
    username: solar
#    password: ${DATABASE_PASSWORD}
    password: solar
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8079
